[project]
name = "api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.38.13",
    "fastapi[standard]>=0.115.12",
]

[tool.uv]
dev-dependencies = [
    "mypy>=1.15.0",
    "pyright>=1.1.400",
    "types-boto3>=1.38.13",
]
