name: Python

on:
  push:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/ruff-action@v3
        with:
          src:  >-
            api
            scripts
      - run: ruff format
      - run: ruff check

  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v5
      - run: uv run --project api mypy ./api
      - run: uv run --project scripts mypy ./scripts
      - run: cd api && uv run pyright .
      - run: cd scripts && uv run pyright .

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  docker:
    runs-on: ubuntu-latest
    needs: [ruff, typing, pre-commit]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPOSITORY }}
          username: nologin
          password: ${{ secrets.DOCKER_SECRET_KEY }}
      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}/api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REPOSITORY:$IMAGE_TAG api
          docker tag $REPOSITORY:$IMAGE_TAG $REPOSITORY:latest
          docker push $REPOSITORY:$IMAGE_TAG
          docker push $REPOSITORY:latest
