name: Python

on:
  push:

permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/ruff-action@v3
        with:
          src:  >-
            api
            scripts
      - run: ruff format
      - run: ruff check

  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v5
      - run: uv run --project api mypy ./api
      - run: uv run --project scripts mypy ./scripts

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  docker:
    runs-on: ubuntu-latest
    needs: [ruff, typing, pre-commit]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REPOSITORY }}
          username: nologin
          password: ${{ secrets.DOCKER_SECRET_KEY }}
      - name: Build, tag, and push docker image to Amazon ECR
        run: |
          docker build -t ${{ secrets.DOCKER_REPOSITORY }}/api:${{ github.sha }} api
          docker push ${{ secrets.DOCKER_REPOSITORY }}/api:${{ github.sha }}
      - name: Update Scaleway container
        uses: scaleway/action-scw@v0
        with:
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-organization-id: ${{ secrets.SCW_ORGANIZATION_ID }}
          args: container container update ${{ secrets.SCW_CONTAINER_ID }} registry-image=${{ secrets.DOCKER_REPOSITORY }}/api:${{ github.sha }}
